# Generated by Django 5.1.2 on 2024-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0006_alter_post_local_government_alter_post_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmanprofile',
            name='tenure_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chairmanprofile',
            name='tenure_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
