# Generated by Django 5.1.2 on 2024-11-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0012_alter_chairmanprofile_local_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmanprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairman_profiles', to='LocalGov.state'),
        ),
    ]
