# Generated by Django 5.1.2 on 2024-11-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0014_remove_comment_parent_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
