# Generated by Django 5.1.2 on 2024-11-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0016_reply_parent_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
    ]
