# Generated by Django 5.1.2 on 2024-11-19 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0017_alter_reply_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmanprofile',
            name='approved_staff',
            field=models.ManyToManyField(blank=True, related_name='approved_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chairmanprofile',
            name='staff_requests',
            field=models.ManyToManyField(blank=True, related_name='staff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('chairman', 'Chairman'), ('staff', 'Staff')], max_length=20),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('desired_chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LocalGov.chairmanprofile')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalGov.localgovernment')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalGov.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_due', models.DateField(blank=True, null=True)),
                ('chairman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LocalGov.chairmanprofile')),
            ],
        ),
    ]
