# Generated by Django 5.1.2 on 2024-11-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0020_staffpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='local_government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LocalGov.localgovernment'),
        ),
    ]
