# Generated by Django 5.1.2 on 2024-11-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0022_alter_staffprofile_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffPost',
        ),
    ]
