# Generated by Django 5.1.2 on 2024-11-19 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0023_delete_staffpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/post_videos/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffpost_author', to=settings.AUTH_USER_MODEL)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffpost_chairman', to='LocalGov.chairmanprofile')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffpost_local_governments', to='LocalGov.localgovernment')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffpost_states', to='LocalGov.state')),
            ],
        ),
    ]
