# Generated by Django 5.1.2 on 2024-11-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0024_staffpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
