# Generated by Django 5.1.2 on 2024-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0027_staffprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile_pictures/'),
        ),
    ]
