# Generated by Django 5.1.2 on 2024-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0031_remove_staffprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpost',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
