# Generated by Django 5.1.2 on 2024-11-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0032_staffpost_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
