# Generated by Django 5.1.2 on 2024-11-25 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0044_remove_comment_staff_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('dislike_count', models.ManyToManyField(blank=True, related_name='disliked_staff_comments', to=settings.AUTH_USER_MODEL)),
                ('like_count', models.ManyToManyField(blank=True, related_name='liked_staff_comments', to=settings.AUTH_USER_MODEL)),
                ('staff_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LocalGov.staffpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='LocalGov.staffpostcomment')),
                ('dislike_count', models.ManyToManyField(blank=True, related_name='disliked_staff_replies', to=settings.AUTH_USER_MODEL)),
                ('like_count', models.ManyToManyField(blank=True, related_name='liked_staff_replies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='LocalGov.staffpostreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
