# Generated by Django 5.1.2 on 2024-11-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0047_staffpostnestedreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpostnestedreply',
            options={'verbose_name': 'Nested Reply', 'verbose_name_plural': 'Nested Replies'},
        ),
    ]
