# Generated by Django 5.1.2 on 2024-11-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0048_alter_staffpostnestedreply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpostreply',
            options={'verbose_name': 'Staff Reply', 'verbose_name_plural': 'Staff Replies'},
        ),
    ]
