# Generated by Django 5.1.2 on 2024-11-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0049_alter_staffpostreply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
