# Generated by Django 5.1.2 on 2024-12-02 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0051_alter_staffpostnestedreply_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_staffposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
