# Generated by Django 5.1.2 on 2024-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0052_post_likes_staffpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytoreply',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
