# Generated by Django 5.1.2 on 2024-12-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalGov', '0053_alter_replytoreply_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replytoreply',
            options={},
        ),
    ]
